/*

  테이블명과 Entity 매핑 정보

*/

const tableEntityMapping = {
  TO0_COMMON_GROUP_CODE: { entityName: "CommonGroupCode", apiPath: "/common/group-code" },
  TO0_COMMON_CODE: { entityName: "CommonCode", apiPath: "/common/code" },
  TO0_AUTH: { entityName: "Auth", apiPath: "/site-admin/auth" },
  TO0_AUTH_GROUP: { entityName: "AuthGroup", apiPath: "/site-admin/auth-group" },
  TO0_AUTH_GROUP_DETAIL: { entityName: "AuthGroupDetail", apiPath: "" },
  TO0_AUTH_USER: { entityName: "AuthUser", apiPath: "" },
  TO0_CORPORATION: { entityName: "Corporation", apiPath: "/site-admin/corporation" },
  TO0_DEPT_MAST: { entityName: "Department", apiPath: "/site-admin/department", alias: "dept" },
  TO0_DUTY_MAIN: { entityName: "Duty", apiPath: "/site-admin/duty" },
  TO0_I18N_MESSAGE: { entityName: "I18NMessage", apiPath: "" },
  TO0_POSITION_MAIN: { entityName: "Position", apiPath: "/site-admin/position" },
  TO0_RANK_MAIN: { entityName: "Rank", apiPath: "/site-admin/rank" },
  TO0_GLOBAL_SETTING: { entityName: "GlobalSetting", apiPath: "/site-admin/global-setting" },
  TO0_SETTING_INFO: { entityName: "SettingInfo", apiPath: "/site-admin/setting" },
  TO0_USER_ADD_JOB: { entityName: "UserAddJob", apiPath: "" },
  TO0_USER_ACTION_LOG: { entityName: "UserActionLog", apiPath: "/site-admin/user-action-log" },
  TO0_USER_MAIN: { entityName: "User", apiPath: "/site-admin/user", alias: "user_main" },
  TO0_PUSH_ALARM: { entityName: "PushAlarm", apiPath: "/push-alarm" },
  TM0_ADMIN_MENU: { entityName: "AdminMenu", apiPath: "/site-admin/admin-menu" },
  TM0_ADMIN_MENU_ACL: { entityName: "AdminMenuAcl", apiPath: "" },
  TM0_MENU: { entityName: "Menu", apiPath: "/site-admin/menu" },
  TM0_MENU_ACL: { entityName: "MenuAcl", apiPath: "" },
  TAS_A_DOC: { entityName: "ApprovalDoc", apiPath: "/approval-doc" },
  TAS_A_DOC_REVISION: { entityName: "ApprovalDocRevision", apiPath: "/approval-revision" },
  TAS_A_DOC_ATTACHED: { entityName: "ApprovalDocLink", apiPath: "/approval-doc-link" },
  TAS_A_DOC_H_MANAGE: { entityName: "ApprovalDocHistoryManage", apiPath: "/approval-doc-history" },
  TAS_A_DOC_INFO: { entityName: "ApprovalDocInfo", apiPath: "/approval-doc-info" },
  TAS_A_LINE: { entityName: "ApprovalLine", apiPath: "/approval-line" },
  TAS_A_LINE_GROUP: { entityName: "ApprovalLineGroup", apiPath: "/approval-line-group" },
  TAS_A_LINE_GROUP_DETAIL: { entityName: "ApprovalLineGroupDetail", apiPath: "/approval-line-group-detail" },
  TAS_A_LINE_HISTORY: { entityName: "ApprovalLineHistory", apiPath: "/approval-line-history" },
  TAS_COR_CONFIG: { entityName: "ApprovalCorConfig", apiPath: "" },
  TAS_CABINET_LINE_MAPPING: { entityName: "ApprovalCabinetLineMapping", apiPath: "/approval-cabinet-line-mapping" },
  TAS_CD_SUB_CONFIG: { entityName: "ApprovalCDSubConfig", apiPath: "" },
  TAS_COR_MANAGER: { entityName: "ApprovalCorporationManager", apiPath: "" },
  TAS_DEPT_CONFIG: { entityName: "ApprovalDepartmentConfig", apiPath: "" },
  TAS_DEPT_MANAGER: { entityName: "ApprovalDepartmentManager", apiPath: "" },
  TAS_DISPLAY: { entityName: "ApprovalDisplayInfo", apiPath: "/approval-display" },
  TAS_DOC_ATTACHED: { entityName: "ApprovalDocFile", apiPath: "/approval-doc-file" },
  TAS_DOC_ATTACHED_HISTORY: { entityName: "ApprovalDocFileHistory", apiPath: "/approval-doc-file-history" },
  TAS_DOC_CABINET: { entityName: "ApprovalDocCabinet", apiPath: "/approval-doc-cabinet" },
  TAS_DOC_NUM: { entityName: "ApprovalDocNum", apiPath: "/approval-doc-num" },
  TAS_DOC_PARSER: { entityName: "ApprovalDocParser", apiPath: "/approval-doc-parser" },
  TAS_DOC_PROGRESS_LOG: { entityName: "ApprovalDocProcessLog", apiPath: "/approval-doc-process-log" },
  TAS_DOC_TYPE: { entityName: "ApprovalDocType", apiPath: "/site-admin/approval-doc-type" },
  TAS_DOC_DATA_MAPPING: { entityName: "ApprovalDocDataMapping", apiPath: "/site-admin/sample-doc-mapping" },
  TAS_DOC_ATTR_DETAIL: { entityName: "ApprovalDocAttrDetail", apiPath: "/approval-doc-attr-detail" },
  TAS_G_RECEIVER: { entityName: "ApprovalDocReceiver", apiPath: "/approval-doc-receiver" },
  TAS_GROUP: { entityName: "ApprovalGroup", apiPath: "/approval-group" },
  TAS_GROUP_DETAIL: { entityName: "ApprovalGroupDetail", apiPath: "/approval-group-detail" },
  TAS_LATEST_DOC: { entityName: "ApprovalLatestSample", apiPath: "/approval-latest-sample" },
  TAS_LIKED_CABINET: { entityName: "ApprovalLikedCabinet", apiPath: "/approval-liked-cabinet" },
  TAS_NUM_CONFIG: { entityName: "ApprovalNumberConfig", apiPath: "/approval-number-config" },
  TAS_OPEN_TYPE: { entityName: "ApprovalOpenType", apiPath: "/approval-open-type" },
  TAS_RECEIVER: { entityName: "ApprovalDocReceiverProcess", apiPath: "/approval-doc-receiver-process" },
  TAS_S_DOC_MAPPING: { entityName: "ApprovalSampleDocMapping", apiPath: "/approval-sample-doc-mapping" },
  TAS_SAMPLE_DOC: { entityName: "ApprovalSampleDoc", apiPath: "/site-admin/sample-doc" },
  TAS_SAMPLE_DOC_A_LINE: { entityName: "ApprovalSampleDocLine", apiPath: "/site-admin/approval-sample-doc-line" },
  TAS_SAMPLE_DOC_A_LINE2: { entityName: "ApprovalSampleDocLine2", apiPath: "/site-admin/approval-sample-doc-line2" },
  TAS_SAMPLE_DOC_REVISION: { entityName: "ApprovalSampleDocRevision", apiPath: "/site-admin/approval-sample-doc-revision" },
  TAS_SEARCH_WORD: { entityName: "ApprovalDocSearchWord", apiPath: "/approval-doc-search-word" },
  TAS_SENDER: { entityName: "ApprovalSender", apiPath: "/approval-sender" },
  TAS_SENDER_HISTORY: { entityName: "ApprovalSenderHistory", apiPath: "/approval-sender-history" },
  TAS_SHARE_CABINET: { entityName: "ApprovalShareCabinet", apiPath: "/approval-share-cabinet" },
  TAS_TMPSAVE: { entityName: "ApprovalTempSaveInfo", apiPath: "/approval-temp-save-info" },
  TAS_USER_ABSENCE: { entityName: "ApprovalUserAbsence", apiPath: "/approval-user-absence" },
  TAS_USER_ABSENCE_HISTORY: { entityName: "ApprovalUserAbsenceHistory", apiPath: "/site-admin/approval-user-absence-history" },
  TAS_USER_CONFIG: { entityName: "ApprovalUserConfig", apiPath: "/approval-user-config" },
  TAS_USER_DOC: { entityName: "ApprovalUserDoc", apiPath: "/approval-user-doc" },
  TRS_DISTRIBUTION: { entityName: "RegistrationDistribution", apiPath: "/registration-distribution" },
  TRS_MOVE_RECORDS: { entityName: "RegistrationMoveRecords", apiPath: "/site-admin/registration-move-records" },
  TRS_R_CABINET: { entityName: "RegistrationCabinet", apiPath: "/registration-cabinet" },
  TRS_RECORDS: { entityName: "RegistrationRecords", apiPath: "/site-admin/record" },
  TRS_RECORDS_SUB: { entityName: "RegistrationRecordsSub", apiPath: "/registration-records-sub" },
  TRS_REGISTRATION: { entityName: "RegistrationDoc", apiPath: "/site-admin/registration" },
  TRS_REGISTRATION_HISTORY: { entityName: "RegistrationDocHistory", apiPath: "/site-admin/registration-doc-history" },
  TRS_SHARE_SECURITY: { entityName: "RegistrationDocShareSecurity", apiPath: "/site-admin/registration-doc-share-security" },
  TRS_U_B_CODE: { entityName: "RegistrationUnitCode", apiPath: "/site-admin/registration-unit-code" },
  TRS_UNOFFICIAL_REGISTRATION: { entityName: "RegistrationUnofficialDoc", apiPath: "/site-admin/registration-unofficial-doc" },
  TO0_COMMON_FILE: { entityName: "CommonFile", apiPath: "/common-file" },
  TO0_INFO_LOG: { entityName: "CommonInfoLog", apiPath: "/site-admin/info-log" },
  TO0_ERROR_LOG: { entityName: "CommonErrorLog", apiPath: "/site-admin/error-log" },
  TO0_NOTIFICATION_ENTRY: { entityName: "CommonNotificationEntry", apiPath: "/site-admin/notification-entry" },
  TO0_NOTIFICATION_LOG: { entityName: "CommonNotificationLog", apiPath: "/site-admin/notification-log" },
  TO0_LOGIN_TOKEN: { entityName: "CommonLoginToken", apiPath: "/site-admin/login-token" },
  TAS_IBK_GM_DOC_MAPPING: { entityName: "IbkGmDocMapping", apiPath: "/site-admin/ibk-gm-doc-mapping" },
  TAS_IBK_LOAN_DOC_MAPPING: { entityName: "IbkLoanDocMapping", apiPath: "/site-admin/ibk-loan-doc-mapping" },
  TAS_DEPT_DOC: { entityName: "ApprovalDeptDoc", apiPath: "/approval-dept-doc" },
  TAS_LIKED_DOC: { entityName: "ApprovalLikedDoc", apiPath: "/approval-liked-doc" },
  TAS_IBK_LINK_DOC_INFO: { entityName: "ApprovalIbkLinkDocInfo", apiPath: "/approval-ibk-link-doc-info" },
  TO0_ORG_SYNC_LOG: { entityName: "OrgSyncLog", apiPath: "/site-admin/org-sync-log" },
};

module.exports = tableEntityMapping;
