/*

  테이블명과 Entity 매핑 정보

*/

const tableEntityMapping = {
  TO0_COMMON_GROUP_CODE: { entityName: "CommonGroupCode", apiPath: "/common/group-code" },
  TO0_COMMON_CODE: { entityName: "CommonCode", apiPath: "/common/code" },
  TO0_AUTH: { entityName: "Auth", apiPath: "/site-admin/auth" },
  TO0_AUTH_GROUP: { entityName: "AuthGroup", apiPath: "/site-admin/auth-group" },
  TO0_AUTH_GROUP_DETAIL: { entityName: "AuthGroupDetail", apiPath: "" },
  TO0_AUTH_USER: { entityName: "AuthUser", apiPath: "" },
  TO0_CORPORATION: { entityName: "Corporation", apiPath: "/site-admin/corporation" },
  TO0_DEPT_MAST: { entityName: "Department", apiPath: "/site-admin/department", alias: "dept" },
  TO0_DUTY_MAIN: { entityName: "Duty", apiPath: "/site-admin/duty" },
  TO0_I18N_MESSAGE: { entityName: "I18NMessage", apiPath: "" },
  TO0_MULTI_LOGIN_INFO: { entityName: "MultiLoginInfo", apiPath: "" },
  TO0_POSITION_MAIN: { entityName: "Position", apiPath: "/site-admin/position" },
  TO0_RANK_MAIN: { entityName: "Rank", apiPath: "/site-admin/rank" },
  TO0_GLOBAL_SETTING: { entityName: "GlobalSetting", apiPath: "/site-admin/global-setting" },
  TO0_SETTING_INFO: { entityName: "SettingInfo", apiPath: "/site-admin/setting" },
  TO0_USER_ADD_JOB: { entityName: "UserAddJob", apiPath: "" },
  TO0_USER_ACTION_LOG: { entityName: "UserActionLog", apiPath: "/site-admin/user-action-log" },
  TO0_USER_MAIN: { entityName: "User", apiPath: "/site-admin/user", alias: "user_main" },
  TO0_PUSH_ALARM: { entityName: "PushAlarm", apiPath: "" },
  TM0_ADMIN_MENU: { entityName: "AdminMenu", apiPath: "/site-admin/admin-menu" },
  TM0_ADMIN_MENU_ACL: { entityName: "AdminMenuAcl", apiPath: "" },
  TM0_MENU: { entityName: "Menu", apiPath: "/site-admin/menu" },
  TM0_MENU_ACL: { entityName: "MenuAcl", apiPath: "" },
  TAS_A_DOC: { entityName: "ApprovalDoc", apiPath: "/approval" },
  TAS_A_DOC_ATTACHED: { entityName: "ApprovalDocLink", apiPath: "" },
  TAS_A_DOC_H_MANAGE: { entityName: "ApprovalDocHisotryManage", apiPath: "" },
  TAS_A_DOC_HISTORY: { entityName: "ApprovalDocHistory", apiPath: "" },
  TAS_A_DOC_INFO: { entityName: "ApprovalDocInfo", apiPath: "" },
  TAS_A_DOC_INTERFACE: { entityName: "ApprovalDocInterface", apiPath: "" },
  TAS_A_DOC_POST: { entityName: "ApprovalDocPost", apiPath: "" },
  TAS_A_LINE: { entityName: "ApprovalLine", apiPath: "" },
  TAS_A_LINE_GROUP: { entityName: "ApprovalLineGroup", apiPath: "" },
  TAS_A_LINE_GROUP_DETAIL: { entityName: "ApprovalLineGroupDetail", apiPath: "" },
  TAS_A_LINE_HISTROY: { entityName: "ApprovalLineHistory", apiPath: "" },
  TAS_COR_CONFIG: { entityName: "ApprovalCorConfig", apiPath: "" },
  TAS_CABINET_LINE_MAPPING: { entityName: "ApprovalCabinetLineMapping", apiPath: "" },
  TAS_CD_SUB_CONFIG: { entityName: "ApprovalCDSubConfig", apiPath: "" },
  TAS_CODE: { entityName: "ApprovalCode", apiPath: "" },
  TAS_COR_MANAGER: { entityName: "ApprovalCorporationManager", apiPath: "" },
  TAS_DEPT_CONFIG: { entityName: "ApprovalDepartmentConfig", apiPath: "" },
  TAS_DEPT_MANAGER: { entityName: "ApprovalDepartmentManager", apiPath: "" },
  TAS_DISPLAY: { entityName: "ApprovalDisplayInfo", apiPath: "" },
  TAS_DOC_ATTACHED: { entityName: "ApprovalDocFile", apiPath: "" },
  TAS_DOC_ATTACHED_HISTORY: { entityName: "ApprovalDocFileHistory", apiPath: "" },
  TAS_DOC_CABINET: { entityName: "ApprovalDocCabinet", apiPath: "" },
  TAS_DOC_NUM: { entityName: "ApprovalDocNum", apiPath: "" },
  TAS_DOC_PARSER: { entityName: "ApprovalDocParser", apiPath: "" },
  TAS_DOC_PROGRESS_LOG: { entityName: "ApprovalDocProcessLog", apiPath: "" },
  TAS_DOC_TYPE: { entityName: "ApprovalDocType", apiPath: "/site-admin/approval-doc-type" },
  TAS_DOC_DATA_MAPPING: { entityName: "ApprovalDocDataMapping", apiPath: "/site-admin/sample-doc-mapping" },
  TAS_DOC_ATTR_DETAIL: { entityName: "ApprovalDocAttrDetail", apiPath: "" },
  TAS_G_RECEIVER: { entityName: "ApprovalDocReceiver", apiPath: "" },
  TAS_GROUP: { entityName: "ApprovalGroup", apiPath: "" },
  TAS_GROUP_DETAIL: { entityName: "ApprovalGroupDetail", apiPath: "" },
  TAS_LATEST_DOC: { entityName: "ApprovalLatestSample", apiPath: "" },
  TAS_LIKED_CABINET: { entityName: '"ApprovalLikedCabinet', apiPath: "" },
  TAS_NUM_CONFIG: { entityName: "ApprovalNumberConfig", apiPath: "" },
  TAS_OPEN_TYPE: { entityName: "ApprovalOpenType", apiPath: "" },
  TAS_PENDING_DOC_MAPPING: { entityName: "ApprovalPendingDocMapping", apiPath: "" },
  TAS_R_STAFF: { entityName: "ApprovalReceiveStaff", apiPath: "" },
  TAS_RECEIVER: { entityName: "ApprovalDocReceiverProcess", apiPath: "" },
  TAS_S_DOC_MAPPING: { entityName: "ApprovalSampleDocMapping", apiPath: "" },
  TAS_SAMPLE_DOC: { entityName: "ApprovalSampleDoc", apiPath: "/site-admin/sample-doc" },
  TAS_SAMPLE_DOC_A_LINE: { entityName: "ApprovalSampleDocLine", apiPath: "" },
  TAS_SAMPLE_DOC_REVISION: { entityName: "ApprovalSampleDocRevision", apiPath: "" },
  TAS_SEARCH_WORD: { entityName: "ApprovalDocSearchWord", apiPath: "" },
  TAS_SENDER: { entityName: "ApprovalSender", apiPath: "" },
  TAS_SENDER_HISTORY: { entityName: "ApprovalSenderHistory", apiPath: "" },
  TAS_SHARE_CABINET: { entityName: "ApprovalShareCabinet", apiPath: "" },
  TAS_STATUS: { entityName: "ApprovalStatusCode", apiPath: "" },
  TAS_TMPSAVE: { entityName: "ApprovalTempSaveInfo", apiPath: "" },
  TAS_USER_ABSENCE: { entityName: "ApprovalUserAbsence", apiPath: "" },
  TAS_USER_ABSENCE_HISTORY: { entityName: "ApprovalUserAbsenceHistory", apiPath: "" },
  TAS_USER_CONFIG: { entityName: "ApprovalUserConfig", apiPath: "" },
  TAS_USER_DOC: { entityName: "ApprovalUserDoc", apiPath: "" },
  TRS_DISTRIBUTION: { entityName: "RegistrationDistribution", apiPath: "" },
  TRS_MOVE_RECORDS: { entityName: "RegistrationMoveRecords", apiPath: "" },
  TRS_R_CABINET: { entityName: "RegistrationCabinet", apiPath: "" },
  TRS_RECORDS: { entityName: "RegistrationRecords", apiPath: "/site-admin/record" },
  TRS_RECORDS_SUB: { entityName: "RegistrationRecordsSub", apiPath: "" },
  TRS_REGISTRATION: { entityName: "RegistrationDoc", apiPath: "/site-admin/registration" },
  TRS_REGISTRATION_HISTROY: { entityName: "RegistrationDocHistory", apiPath: "" },
  TRS_SHARE_SECURITY: { entityName: "RegistrationDocShareSecurity", apiPath: "" },
  TRS_U_B_CODE: { entityName: "RegistrationUnitCode", apiPath: "/site-admin/registration-unit-code" },
  TRS_UNOFFICIAL_REGISTRATION: { entityName: "RegistrationUnofficialDoc", apiPath: "" },
  TO0_COMMON_FILE: { entityName: "CommonFile", apiPath: "" },
  TO0_INFO_LOG: { entityName: "CommonInfoLog", apiPath: "/site-admin/info-log" },
  TO0_ERROR_LOG: { entityName: "CommonErrorLog", apiPath: "/site-admin/error-log" },
  TO0_NOTIFICATION_ENTRY: { entityName: "CommonNotificationEntry", apiPath: "/site-admin/notification-entry" },
  TO0_NOTIFICATION_LOG: { entityName: "CommonNotificationLog", apiPath: "/site-admin/notification-log" },
  TO0_LOGIN_TOKEN: { entityName: "CommonLoginToken", apiPath: "/site-admin/login-token" },
  TAS_IBK_GM_DOC_MAPPING: { entityName: "IbkGmDocMapping", apiPath: "/site-admin/ibk-gm-doc-mapping" },
  TAS_IBK_LOAN_DOC_MAPPING: { entityName: "IbkLoanDocMapping", apiPath: "/site-admin/ibk-loan-doc-mapping" },
  TAS_SAMPLE_DOC_A_LINE2: { entityName: "ApprovalSampleDocLine2", apiPath: "" },
  TAS_DEPT_DOC: { entityName: "ApprovalDeptDoc", apiPath: "" },
  TAS_LIKED_DOC: { entityName: '"ApprovalLikedDoc', apiPath: "" },
  TAS_IBK_LINK_DOC_INFO: { entityName: '"ApprovalIbkLinkDocInfo', apiPath: "" },
};

module.exports = tableEntityMapping;
